include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-0asq

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: onb-us-enum-jb-tp-fn-7c9c935a-f198-4e20-af8e-6e8595c5b5fd
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-0asq
  environment:
    name: onb-us-enum-jb-tp-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-06T10:30:06Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: onb-us-enum-jb-tp-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      SpecializationTimeout: 120
    StrategyType: execution
  concurrency: 500
  environment:
    name: onb-us-enum-jb-tp-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: onb-us-enum-jb-tp-fn-7c9c935a-f198-4e20-af8e-6e8595c5b5fd
      namespace: default
  requestsPerPod: 10000
  resources:
    requests:
      cpu: 128m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 256Mi
